Repository KnpLabs/DictionaryBundle, pull requests merged in 2018-10, with the labels that each got.

#77 Fixed normalized hyphen in dictionary items name. #75
  src/Knp/DictionaryBundle/DependencyInjection/Configuration.php
Labels: Ready to review

#78 Added ExtendedDictionary
  spec/Knp/DictionaryBundle/Dictionary/ExtendedDictionarySpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/ExtendedSpec.php
  src/Knp/DictionaryBundle/DependencyInjection/Configuration.php
  src/Knp/DictionaryBundle/Dictionary/ExtendedDictionary.php
  src/Knp/DictionaryBundle/Dictionary/Factory/Extended.php
  src/Knp/DictionaryBundle/Resources/config/dictionary.xml
Labels: Ready to review

#79 Apply new cs fixing rule
  .php_cs.dist
  .php_cs.rules.json
  composer.json
  spec/Knp/DictionaryBundle/DataCollector/DictionaryDataCollectorSpec.php
  spec/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryBuildingPassSpec.php
  spec/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryFactoryBuildingPassSpec.php
  spec/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryRegistrationPassSpec.php
  spec/Knp/DictionaryBundle/DependencyInjection/ConfigurationSpec.php
  spec/Knp/DictionaryBundle/DependencyInjection/KnpDictionaryExtensionSpec.php
  spec/Knp/DictionaryBundle/Dictionary/CallableDictionarySpec.php
  spec/Knp/DictionaryBundle/Dictionary/DictionaryRegistrySpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/CallableFactorySpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/FactoryAggregateSpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/KeyValueSpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/ValueAsKeySpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/ValueSpec.php
  spec/Knp/DictionaryBundle/Dictionary/SimpleDictionarySpec.php
  spec/Knp/DictionaryBundle/Dictionary/TraceableDictionarySpec.php
  spec/Knp/DictionaryBundle/Dictionary/ValueTransformer/ConstantTransformerSpec.php
  spec/Knp/DictionaryBundle/Dictionary/ValueTransformer/TransformerAggregateSpec.php
  spec/Knp/DictionaryBundle/Exception/DictionaryNotFoundExceptionSpec.php
  spec/Knp/DictionaryBundle/Faker/Provider/DictionarySpec.php
  spec/Knp/DictionaryBundle/Form/Type/DictionaryTypeSpec.php
  spec/Knp/DictionaryBundle/KnpDictionaryBundleSpec.php
  spec/Knp/DictionaryBundle/Twig/DictionaryExtensionSpec.php
  spec/Knp/DictionaryBundle/Validator/Constraints/DictionarySpec.php
  spec/Knp/DictionaryBundle/Validator/Constraints/DictionaryValidatorSpec.php
  src/Knp/DictionaryBundle/DataCollector/DictionaryDataCollector.php
  src/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryBuildingPass.php
  src/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryFactoryBuildingPass.php
  src/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryRegistrationPass.php
  src/Knp/DictionaryBundle/DependencyInjection/Compiler/DictionaryTracePass.php
  src/Knp/DictionaryBundle/DependencyInjection/Configuration.php
  src/Knp/DictionaryBundle/DependencyInjection/KnpDictionaryExtension.php
  src/Knp/DictionaryBundle/Dictionary.php
  src/Knp/DictionaryBundle/Dictionary/CallableDictionary.php
  src/Knp/DictionaryBundle/Dictionary/DictionaryRegistry.php
  src/Knp/DictionaryBundle/Dictionary/Factory.php
  src/Knp/DictionaryBundle/Dictionary/Factory/CallableFactory.php
  src/Knp/DictionaryBundle/Dictionary/Factory/FactoryAggregate.php
  src/Knp/DictionaryBundle/Dictionary/Factory/KeyValue.php
  src/Knp/DictionaryBundle/Dictionary/Factory/Value.php
  src/Knp/DictionaryBundle/Dictionary/Factory/ValueAsKey.php
  src/Knp/DictionaryBundle/Dictionary/SimpleDictionary.php
  src/Knp/DictionaryBundle/Dictionary/TraceableDictionary.php
  src/Knp/DictionaryBundle/Dictionary/ValueTransformer.php
  src/Knp/DictionaryBundle/Dictionary/ValueTransformer/ConstantTransformer.php
  src/Knp/DictionaryBundle/Dictionary/ValueTransformer/TransformerAggregate.php
  src/Knp/DictionaryBundle/Exception/DictionaryNotFoundException.php
  src/Knp/DictionaryBundle/Faker/Provider/Dictionary.php
  src/Knp/DictionaryBundle/Form/Type/DictionaryType.php
  src/Knp/DictionaryBundle/KnpDictionaryBundle.php
  src/Knp/DictionaryBundle/Twig/DictionaryExtension.php
  src/Knp/DictionaryBundle/Validator/Constraints/Dictionary.php
  src/Knp/DictionaryBundle/Validator/Constraints/DictionaryValidator.php
Labels: Ready to review

#80 Added documentation for ExtendedDictionary
  README.md
Labels: Ready to review, documentation

#81 Fix hard spaces breaking the markdown formatting
  README.md
Labels: Ready to review, documentation

#83 Added CombinedDictionary
  spec/Knp/DictionaryBundle/Dictionary/CombinedDictionarySpec.php
  spec/Knp/DictionaryBundle/Dictionary/Factory/CombinedSpec.php
  src/Knp/DictionaryBundle/DependencyInjection/Configuration.php
  src/Knp/DictionaryBundle/Dictionary/CombinedDictionary.php
  src/Knp/DictionaryBundle/Dictionary/Factory/Combined.php
  src/Knp/DictionaryBundle/Resources/config/dictionary.xml
Labels: Ready to review

#84 Refactoring of ExtendedDictionary to use CombinedDictionary implement…
  README.md
  spec/Knp/DictionaryBundle/Dictionary/ExtendedDictionarySpec.php
  src/Knp/DictionaryBundle/Dictionary/ExtendedDictionary.php
  src/Knp/DictionaryBundle/Dictionary/Factory/Extended.php
Labels: Ready to review

#96 Fix #89
  spec/Knp/DictionaryBundle/Dictionary/ValueTransformer/ConstantTransformerSpec.php
  src/Knp/DictionaryBundle/Dictionary/ValueTransformer/ConstantTransformer.php
Labels: Ready to review, bug
